### ISSUE TITLE
Add a callback for dialog closure

### ISSUE THREAD

**Issue by crrobinson14** [auth0/widget#103]
In some apps it's useful to know when the user has closed the authentication dialog without completing a sign-in. This isn't a failure - I'm talking about hitting the 'X' button. When auth is being used as a 'gate' for some protected resource, you need to know when to trigger an alternate action like notifying the user that a login is actually required for the next step.

**Comment by cristiandouce** [comment]
And you can follow this guide: https://github.com/auth0/lock/wiki/Migration-Guide :grinning:

**Comment by crrobinson14** [comment]
@cristiandouce Thanks for the reply...but this doesn't seem to work for me. We've already switched to the new Lock dialog, and that isn't an EventEmitter so it has no .on() method. The migration guide doesn't talk about what to do here, and Lock doesn't appear to have a mechanism for this, either. Any ideas?

**Comment by crrobinson14** [comment]
Does it help at all to know that we're using the additional Angular service you've provided? It provides success and error callbacks, but neither is fired if the user just closes the dialog. Just to be clear, we want to allow dialog closure - we just want to know when it's happened!

**Comment by cristiandouce** [comment]
Hi @crrobinson14 the new Lock is an `EventEmitter` as shown [here](https://github.com/auth0/lock/blob/master/index.js#L67)

Of course the angular lib is a wrapper on top of an Auth0Lock instance. You will have to refer to that lib to learn how to reach the Lock instance an register your event (or any other direct interaction with the Lock instance).

If I'm not wrong, from your `auth` provider, you should get the `auth0lib` property which will be the Lock instance you may be looking for. [Here](https://github.com/auth0/auth0-angular/blob/master/examples/refresh-token/app.js#L71) like in all the other auth0-angular examples, the `auth.auth0lib` property should be the Lock instance we are talking about.

I'm sure @mgonto could confirm that.

Thanks!

**Comment by crrobinson14** [comment]
Thanks @cristiandouce. This was close enough to get me the rest of the way. Here's what ended up working:

            auth.config.auth0lib.on('hidden', function() {
                console.log('closed');
            });

**Comment by crrobinson14** [comment]
@cristiandouce Any update on this?

**Comment by pose** [comment]
Hi @crrobinson14,

I've created an issue at Auth0 Lock as Auth0 Widget is deprecated: https://github.com/auth0/lock/issues/124

You can follow up the issue there.

Best Regards,

**Comment by pose** [comment]
Hey @mgonto,

Can you take a look at this issue? The  **resolving/rejecting a promise-based auth checker** seems to be `auth0-angular` related. Let me know what you need so I can make the necessary changes in Auth0.js and Auth0 Lock to make it work.

Thanks in advance,

**Comment by crrobinson14** [comment]
Just to add some context in case it wasn't clear, this need comes from the desire to have a public site but with some functions/views that require login. It's common that, when a user cancels out of the auth process, you need to do something special: fire an analytic (for people tracking acquisition pipelines), show the user a helpful message, etc. There is a 'hidden' event, but it's fired for all reasons that close the dialog, so it can't be used specifically to drive cancel-triggered events.

Here's an (summarized) example of what we're trying to fill out:

```javascript
      return $q(function(resolve, reject) {
            auth.config.auth0lib.on('hidden', function(e) {
                // We get this event when the dialog is closed, but for ALL reasons: success, failure,
                // and cancellation. So we can't use it to reject the promise.
                log.debug('Closed dialog');
                //reject('Closed');
            });

            auth.signin({
                socialBigButtons: true
            }, function(profile, token) {
                log.debug('Auth successful', auth, profile, token);

                self.authProfile = profile;
                store.set('profile', profile);

                // This tells the caller we were successful. We just can't tell the caller we failed.
                resolve(auth);
            }, function() {
                // Here we know we _definitely_ failed so we can reject. But we don't come here on 'cancel'.
                // Actually, we've never had our code arrive here so we're not even sure what might trigger it.
                log.debug('Login failed.');
                reject('Login failed.');
            });
        });
```

**Comment by cristiandouce** [comment]
@crrobinson14 Could you?:

```js
auth.config.auth0lib.on('ready', function () {
  $('.a0-close', this.container).once('click', oncancelclick);
});

function oncancelclick (ev) {
  // fire up your analytics events here!
}
```

It is in fact an interesting feature request to add more `data` to the `hidden` callback arguments like the type of hide triggering like you say: `cancel|success`. I can't think now of any other.

@pose what do you think about this?

**Comment by crrobinson14** [comment]
@cristiandouce I supposed we could... but that requires us to tightly couple the application logic to the Auth0 popup UI. Suppose we or another client wanted to use the popup flow where these DOM elements aren't available? Suppose you alter your code to rename the class this element has applied to it? Wouldn't it be better to do this through a proper event notification so that it can be a documented feature, part of the "contract" for how the component behaves? I can send a PR for this if you like...

**Comment by crrobinson14** [comment]
I missed your other comment - I agree about the error handling. Since Auth0 handles those internally, exposing them is just a nice-to-have - success|cancel are the critical ones. You might want to think about customers who want to drive analytics or QOS/RUM tools like NewRelic off of it, though...

**Comment by cristiandouce** [comment]
@crrobinson14 check auth0/lock#82 on the analytics

BTW, the `oncancelclick` could trigger an `events bus` service of yours that broadcasts to whatever other services (like analytics for example) need to listen for the widget actions.

For example:

```js
// where your auth provider is
var bus = require('bus');

auth.config.auth0lib.on('ready', function () {
  $('.a0-close', this.container).once('click', oncancelclick);
});

function oncancelclick (ev) {
  // fire up your analytics events here!
  bus.emit('widget closed', ev);
}

// public/your-analytics-service.js
var bus = require('bus');
bus.on('widget closed', function (ev) {
  // trigger analytics
  analytics.emit('user close login', window.location.toString());
});

// public/on-some-other-service.js
var bus = require('bus');
bus.on('widget closed', function (ev) {
// do other service stuff
});
```

Does this make any sense?

Of course we are willing to integrate this in the lib, but yet I'd like to see you go through this in the mean time :grinning:

**Comment by crrobinson14** [comment]
This is an AngularJS app. We already have a broadcast mechanism as part of the framework, and we already have a hack in place to tolerate not being told which way the user closed the lightbox. Detecting clicks on `.a0-close` totally works. All we're asking for here is to not require an (undocumented) hack like this. Renaming the class shouldn't be a breaking change.
