### ISSUE TITLE
'KeyboardEvent.keyLocation' is deprecated warning

### ISSUE THREAD

**Issue by newtriks** [auth0/widget#104]
I am seeing the following warning in the Chrome console from `auth0-widget-4.1.js:3261`: 

`'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location' instead.`

**Comment by cristiandouce** [comment]
Hi, you should update to https://github.com/auth0/lock if possible.

Here is a migration guide you can go through: https://github.com/auth0/lock/wiki/Migration-Guide

Let us know how it goes! :grinning:
